### ISSUE TITLE
mail的几个问题

### ISSUE THREAD

**Issue by Like-whale** [malizhigithub/CRM#10]
您好！我下载了该项目的代码，关于mail配置文件想请问几个问题。这个mail是如何配置的呢？因为我现在还是小白，没用过mail。如果可以的话能给我一份软件的设计文档么？感谢！

**Comment by malizhigithub** [comment]
您好，设计文档没有写到mail方面配置的问题，关于mail的配置可以查看这篇文章




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Like-whale"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月17日(星期三) 上午9:55
收件人:&nbsp;"malizhigithub/CRM"<CRM@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[malizhigithub/CRM] mail的几个问题 (#10)





 
您好！我下载了该项目的代码，关于mail配置文件想请问几个问题。这个mail是如何配置的呢？因为我现在还是小白，没用过mail。如果可以的话能给我一份软件的设计文档么？感谢！
