### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by 13120241790** [malizhigithub/CRM#17]
请问一下这套管理系统能实现管理员 和 员工等多个角色登录吗。比如员工在 web 端登录去录入客户的一些信息资料。

**Comment by malizhigithub** [comment]
可以的

**Comment by malizhigithub** [comment]
> 请问一下这套管理系统能实现管理员 和 员工等多个角色登录吗。比如员工在 web 端登录去录入客户的一些信息资料。



> 譬如员工在网页端登录去登录客户的一些信息资料。

**Comment by malizhigithub** [comment]
> 譬如员工在网页端登录去登录客户的一些信息资料。

可以的
