### ISSUE TITLE
需要软件设计文档

### ISSUE THREAD

**Issue by moyuking233** [malizhigithub/CRM#2]
老兄，首先很谢谢你贡献出了这么好的一个项目，但由于我的水平不够仍然不能够完全消化这个项目。事实上，我有很多个疑问，如果有一份软件设计文档那是再好不过了。m13411907763@163.com

**Comment by malizhigithub** [comment]
发你邮件啦

**Comment by anzzz999** [comment]
> 发你邮件啦
这个项目写的挺好的，不过我一下子看不太懂，能能分享一份设计文档给我吗？谢谢了.995127051@qq.com

**Comment by childyet** [comment]
您好，能发我一份吗，有些地方我也没办法完全理解，需要一些帮助 740123621@11.com

**Comment by malizhigithub** [comment]
发送过去了

**Comment by umbrella123456** [comment]
老哥，小弟我是一个新手菜鸟程序员，和前面几位大哥一样，也有很多不懂的地方，如果可以的话能不能也分享一份文档给我，小弟感激不尽2846635310@qq.com

**Comment by zhangbinnn** [comment]
同求设计文档，1439825147@qq.com感谢大哥

**Comment by a18219190615** [comment]
你好，正在学习ssm框架，请问能发一份设计文档，1447045543@qq.com

**Comment by a18219190615** [comment]
你好，正在学习ssm框架，请问能发一份设计文档吗，非常感谢！1447045543@qq.com

**Comment by malizhigithub** [comment]
&nbsp;
微云的文件
CRM文档.rar(555.0K)




已发送
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "malizhigithub/CRM"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月5日(星期一) 下午3:25
收件人:&nbsp;"malizhigithub/CRM"<CRM@noreply.github.com&gt;;
抄送:&nbsp;"马立志"<30405935@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [malizhigithub/CRM] 需要软件设计文档 (#2)





 
同求设计文档，1439825147@qq.com感谢大哥
