### ISSUE TITLE
无法登陆进去

### ISSUE THREAD

**Issue by LDTonyNb1** [malizhigithub/crm#3]
如何在测试类中添加用户，我操作的时候为失败

**Comment by zycjds** [comment]
获取一下最新代码

**Comment by zycjds** [comment]
> 如何在测试类中添加用户，我操作的时候为失败

获取一下最新代码

**Comment by zycjds** [comment]
您好  登陆进去之后是404页面 请问是什么原因  数据库用的是您给的这个

**Comment by LDTonyNb1** [comment]
> > 如何在测试类中添加用户，我操作的时候为失败
> 
> 获取一下最新代码

我是获取的最新代码呀，可以讲解下具体操作步骤吗，学习学习，谢谢

**Comment by zycjds** [comment]
> > > 如何在测试类中添加用户，我操作的时候为失败
> > 
> > 
> > 获取一下最新代码
> 
> 我是获取的最新代码呀，可以讲解下具体操作步骤吗，学习学习，谢谢

一开始我也添加不了,后来作者两天前修复了这个问题,现在是可以的,你看你数据库是否连接正确

**Comment by LDTonyNb1** [comment]
> > > 如何在测试类中添加用户，我操作的时候为失败
> > 
> > 
> > 获取一下最新代码
> 
> 我是获取的最新代码呀，可以讲解下具体操作步骤吗，学习学习，谢谢



> > > > 如何在测试类中添加用户，我操作的时候为失败
> > > 
> > > 
> > > 获取一下最新代码
> > 
> > 
> > 我是获取的最新代码呀，可以讲解下具体操作步骤吗，学习学习，谢谢
> 
> 一开始我也添加不了,后来作者两天前修复了这个问题,现在是可以的,你看你数据库是否连接正确

你已经成功了吗，教我操作操作，可以加你的qq吗？
