### ISSUE TITLE
需要详细设计文档帮助理解

### ISSUE THREAD

**Issue by Alberleec** [malizhigithub/CRM#7]
老哥，有部分逻辑没办法理清，想要设计文档帮助理解一下

**Comment by malizhigithub** [comment]
&nbsp;
微云的文件
CRM文档.rar(555.0K)


这份是设计文档，不乱传哈




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"childyet"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月31日(星期二) 中午11:17
收件人:&nbsp;"malizhigithub/CRM"<CRM@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[malizhigithub/CRM] 需要详细设计文档帮助理解 (#7)





 
老哥，有部分逻辑没办法理清，想要设计文档帮助理解一下 740123621@qq.com

**Comment by malizhigithub** [comment]
发送过去了
