### ISSUE TITLE
关于数据库脚本

### ISSUE THREAD

**Issue by huangsiyuan666** [malizhigithub/CRM#8]
作者大神您好， 项目代码我已经过down下来了并且很仔细的研究过， 发现很不错， 但是有一点就是， 能不能提供下数据库脚本还有设计文档？ 我的邮箱useraction666@163.com;

**Comment by malizhigithub** [comment]
项目数据库在一级目录中，命名为CRM.sql，其中‘user’表为账户表
设计文档发过去了

**Comment by huangsiyuan666** [comment]
好的， 收到， 十分感谢



在 2020-04-17 17:40:12，"malizhi" <notifications@github.com> 写道：

项目数据库在一级目录中，命名为CRM.sql，其中‘user’表为账户表
设计文档发过去了

**Comment by huangsiyuan666** [comment]
你好，请问CRM系统中，角色修改， 角色添加，角色权限分配这几个功能是没有提供吗？



在 2020-04-17 17:40:12，"malizhi" <notifications@github.com> 写道：

项目数据库在一级目录中，命名为CRM.sql，其中‘user’表为账户表
设计文档发过去了

**Comment by malizhigithub** [comment]
系统管理（一级菜单）-角色管理（二级菜单） 就是此部分的功能



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "huangsiyuan666"<notifications@github.com&gt;; 
发送时间: 2020年5月21日(星期四) 下午5:11
收件人: "malizhigithub/CRM"<CRM@noreply.github.com&gt;; 
抄送: "马立志"<30405935@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [malizhigithub/CRM] 关于数据库脚本 (#8)





 你好，请问CRM系统中，角色修改， 角色添加，角色权限分配这几个功能是没有提供吗？
 
 
 
 在 2020-04-17 17:40:12，"malizhi" <notifications@github.com&gt; 写道：
 
 项目数据库在一级目录中，命名为CRM.sql，其中‘user’表为账户表
 设计文档发过去了

**Comment by huangsiyuan666** [comment]
好的，已经加载出来了，之前没有加载到；请问下该项目的mybatis的逆向生成的配置文件有没有？在工程里我没有找到，如果有的话能否发我一份？



在 2020-05-22 20:04:26，"malizhi" <notifications@github.com> 写道：

系统管理（一级菜单）-角色管理（二级菜单） 就是此部分的功能



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "huangsiyuan666"<notifications@github.com&gt;;
发送时间: 2020年5月21日(星期四) 下午5:11
收件人: "malizhigithub/CRM"<CRM@noreply.github.com&gt;;
抄送: "马立志"<30405935@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;;
主题: Re: [malizhigithub/CRM] 关于数据库脚本 (#8)





你好，请问CRM系统中，角色修改， 角色添加，角色权限分配这几个功能是没有提供吗？



在 2020-04-17 17:40:12，"malizhi" <notifications@github.com&gt; 写道：

项目数据库在一级目录中，命名为CRM.sql，其中‘user’表为账户表
设计文档发过去了

**Comment by malizhigithub** [comment]
逆向生成的映射文件在src\main\resources\mapper下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"huangsiyuan666"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月29日(星期五) 中午11:06
收件人:&nbsp;"malizhigithub/CRM"<CRM@noreply.github.com&gt;;
抄送:&nbsp;"马立志"<30405935@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [malizhigithub/CRM] 关于数据库脚本 (#8)





 好的，已经加载出来了，之前没有加载到；请问下该项目的mybatis的逆向生成的配置文件有没有？在工程里我没有找到，如果有的话能否发我一份？
 
 
 
 在 2020-05-22 20:04:26，"malizhi" <notifications@github.com&gt; 写道：
 
 系统管理（一级菜单）-角色管理（二级菜单） 就是此部分的功能
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
 发件人: "huangsiyuan666"<notifications@github.com&amp;gt;;
 发送时间: 2020年5月21日(星期四) 下午5:11
 收件人: "malizhigithub/CRM"<CRM@noreply.github.com&amp;gt;;
 抄送: "马立志"<30405935@qq.com&amp;gt;; "Comment"<comment@noreply.github.com&amp;gt;;
 主题: Re: [malizhigithub/CRM] 关于数据库脚本 (#8)
 
 
 
 
 
 你好，请问CRM系统中，角色修改， 角色添加，角色权限分配这几个功能是没有提供吗？
 
 
 
 在 2020-04-17 17:40:12，"malizhi" <notifications@github.com&amp;gt; 写道：
 
 项目数据库在一级目录中，命名为CRM.sql，其中‘user’表为账户表
 设计文档发过去了

**Comment by sherlock515** [comment]
> 作者大神您好， 项目代码我已经过down下来了并且很仔细的研究过， 发现很不错， 但是有一点就是， 能不能提供下数据库脚本还有设计文档？ 我的邮箱[useraction666@163.com](mailto:useraction666@163.com);

您好，我也想要设计文档，请问可以发给我一份吗？我的邮箱是495616318@qq.com    十分感谢您

**Comment by sherlock515** [comment]
> 项目数据库在一级目录中，命名为CRM.sql，其中‘user’表为账户表
> 设计文档发过去了

您好，请问方便提供技术文档学习一下吗？我的邮箱是495616318@qq.com    非常感谢您

**Comment by 2285523396** [comment]
> 项目数据库在一级目录中，命名为CRM.sql，其中‘user’表为账户表
> 设计文档发过去了

大神，设计文档可以也发给我一份嘛，邮箱是2285523396@qq.com

**Comment by WUSHUAIHANG** [comment]
也求一份设计文档，万分感谢。qeer08@163.com

**Comment by Frank20180428** [comment]
大神，设计文档可以也发给我一份嘛，邮箱是3280735727@qq.com，万分感谢！
